import type { Metadata } from "next";
import "./globals.css";
import { BlocksProvider } from "@/context/blocks.context";

export const metadata: Metadata = {
   title: "Create Next App",
   description: "Generated by create next app",
};

export default function BlocksLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <html lang="en">
         <body>
            <BlocksProvider>{children}</BlocksProvider>
         </body>
      </html>
   );
}
